export const AUTO_DURATION_MIN_SECONDS = 4;
export const AUTO_DURATION_MAX_SECONDS = 40;
export const AUTO_DURATION_PIXELS_PER_SECOND = 800;
export const LOCALHOST_RETRY_INTERVAL_MS = 500;
export const STABILIZE_DELAY_MS = 500;
export const PREFLIGHT_STEP_DELAY_MS = 120;
export const PREFLIGHT_STABLE_ROUNDS = 3;
export const PREFLIGHT_MAX_SCROLL_HEIGHT = 30_000;
